

namespace Antijank.Debugging {

  
  public enum METAHOST_POLICY_FLAGS {

    METAHOST_POLICY_HIGHCOMPAT,

    METAHOST_POLICY_APPLY_UPGRADE_POLICY = 8,

    METAHOST_POLICY_EMULATE_EXE_LAUNCH = 16,

    METAHOST_POLICY_SHOW_ERROR_DIALOG = 32,

    METAHOST_POLICY_USE_PROCESS_IMAGE_PATH = 64,

    METAHOST_POLICY_ENSURE_SKU_SUPPORTED = 128,

    METAHOST_POLICY_IGNORE_ERROR_MODE = 4096

  }

}